"""Generate dnsmasq config and enable/disable the local DHCP service."""

from __future__ import annotations

import ipaddress
import logging
import os
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from app.core.config import settings
from app.models import AppSetting, DhcpLease, DhcpPool, DhcpReservation, DhcpServer

logger = logging.getLogger("nexusops.dhcp")
LOCAL_SERVER_NAME = "NexusOps DHCP"
SETTING_KEY = "dhcp_local_enabled"


@dataclass
class ParsedLease:
    ip_address: str
    mac_address: str
    hostname: str | None
    expires: datetime | None
    status: str = "active"


def data_dir() -> Path:
    path = Path(settings.dhcp_data_dir)
    return path


def ensure_data_dir() -> Path:
    path = data_dir()
    path.mkdir(parents=True, exist_ok=True)
    return path


def enabled_flag() -> Path:
    return data_dir() / "enabled"


def config_path() -> Path:
    return data_dir() / "dnsmasq.conf"


def lease_path() -> Path:
    return data_dir() / "dnsmasq.leases"


def normalize_mac(mac: str) -> str:
    raw = (mac or "").strip().lower().replace("-", ":").replace(".", "")
    if ":" not in raw and len(raw) == 12:
        raw = ":".join(raw[i : i + 2] for i in range(0, 12, 2))
    return raw


def parse_dnsmasq_leases(text: str, now: datetime | None = None) -> list[ParsedLease]:
    now = now or datetime.now(timezone.utc)
    rows: list[ParsedLease] = []
    for line in text.splitlines():
        parts = line.split()
        if len(parts) < 3:
            continue
        try:
            expiry = int(parts[0])
        except ValueError:
            continue
        mac = normalize_mac(parts[1])
        ip = parts[2]
        hostname = parts[3] if len(parts) > 3 and parts[3] not in {"*", ""} else None
        expires = datetime.fromtimestamp(expiry, tz=timezone.utc) if expiry > 0 else None
        status = "expired" if expires and expires < now else "active"
        rows.append(ParsedLease(ip_address=ip, mac_address=mac, hostname=hostname, expires=expires, status=status))
    return rows


def render_dnsmasq(pools: list[DhcpPool], reservations: list[DhcpReservation]) -> str:
    lines = [
        "# Generated by NexusOps. Do not edit.",
        "port=0",
        "bind-dynamic",
        "except-interface=lo",
        "dhcp-authoritative",
        "log-dhcp",
        f"dhcp-leasefile={lease_path()}",
        "dhcp-lease-max=1024",
    ]
    if not pools:
        raise ValueError("Add at least one DHCP pool before enabling the local server")
    for pool in pools:
        subnet = ipaddress.ip_network(pool.subnet, strict=False)
        start = ipaddress.ip_address(pool.range_start)
        end = ipaddress.ip_address(pool.range_end)
        if start not in subnet or end not in subnet:
            raise ValueError(f"Pool {pool.range_start}-{pool.range_end} is outside {pool.subnet}")
        if int(end) < int(start):
            raise ValueError(f"Pool range {pool.range_start}–{pool.range_end} is reversed")
        lease = max(int(pool.lease_time or 86400), 60)
        netmask = subnet.netmask
        lines.append(f"dhcp-range=set:pool{pool.id},{start},{end},{netmask},{lease}s")
        if pool.gateway:
            lines.append(f"dhcp-option=tag:pool{pool.id},3,{pool.gateway}")
        if pool.dns_servers:
            dns = ",".join(item.strip() for item in pool.dns_servers.split(",") if item.strip())
            if dns:
                lines.append(f"dhcp-option=tag:pool{pool.id},6,{dns}")
    for res in reservations:
        mac = normalize_mac(res.mac_address)
        host = (res.hostname or "").replace(" ", "-")
        extra = f",{host}" if host else ""
        lines.append(f"dhcp-host={mac},{res.ip_address}{extra}")
    return "\n".join(lines) + "\n"


def write_config(text: str) -> Path:
    ensure_data_dir()
    path = config_path()
    path.write_text(text, encoding="utf-8")
    return path


def is_enabled() -> bool:
    return enabled_flag().exists()


def set_enabled(on: bool) -> None:
    ensure_data_dir()
    flag = enabled_flag()
    if on:
        flag.write_text("1\n", encoding="utf-8")
    elif flag.exists():
        flag.unlink()


def process_running() -> bool:
    lease = lease_path()
    if is_enabled() and config_path().exists():
        # The sidecar loop starts dnsmasq shortly after the flag appears.
        return is_enabled()
    if lease.exists() and (os.path.getmtime(lease) > (datetime.now().timestamp() - 90)):
        return True
    return False


def ensure_local_server(db) -> DhcpServer:
    server = db.query(DhcpServer).filter(DhcpServer.kind == "local").first()
    if server:
        return server
    server = DhcpServer(
        name=LOCAL_SERVER_NAME,
        host="127.0.0.1",
        description="Local NexusOps DHCP (dnsmasq). Disable DHCP on the router before enabling this.",
        status="stopped",
        kind="local",
    )
    db.add(server)
    db.commit()
    db.refresh(server)
    return server


def persist_setting(db, enabled: bool) -> None:
    row = db.query(AppSetting).filter(AppSetting.key == SETTING_KEY).first()
    if row is None:
        db.add(AppSetting(key=SETTING_KEY, value="true" if enabled else "false", description="Local DHCP enabled"))
    else:
        row.value = "true" if enabled else "false"
    db.commit()


def seed_pool_from_ipam(db, server: DhcpServer) -> DhcpPool | None:
    from app.models import Subnet

    if db.query(DhcpPool).filter(DhcpPool.server_id == server.id).first():
        return None
    subnet = db.query(Subnet).filter(Subnet.status == "active").order_by(Subnet.id).first()
    if not subnet:
        return None
    try:
        network = ipaddress.ip_network(subnet.cidr, strict=False)
    except ValueError:
        return None
    hosts = list(network.hosts())
    if len(hosts) < 20:
        return None
    start = hosts[max(len(hosts) // 4, 10)]
    end = hosts[min(len(hosts) - 5, len(hosts) * 3 // 4)]
    pool = DhcpPool(
        server_id=server.id,
        subnet=str(network),
        range_start=str(start),
        range_end=str(end),
        gateway=subnet.gateway,
        dns_servers=None,
        description="Seeded from IPAM",
    )
    db.add(pool)
    db.commit()
    db.refresh(pool)
    return pool


def apply_pools(db) -> str:
    server = ensure_local_server(db)
    seed_pool_from_ipam(db, server)
    pools = db.query(DhcpPool).filter(DhcpPool.server_id == server.id).all()
    reservations: list[DhcpReservation] = []
    for pool in pools:
        reservations.extend(pool.reservations)
    text = render_dnsmasq(pools, reservations)
    write_config(text)
    return text


def ingest_local_leases(db) -> int:
    if not lease_path().exists():
        return 0
    server = ensure_local_server(db)
    pools = db.query(DhcpPool).filter(DhcpPool.server_id == server.id).all()
    parsed = parse_dnsmasq_leases(lease_path().read_text(encoding="utf-8", errors="replace"))
    return upsert_leases(db, parsed, pools, source="local")


def ip_in_pool(ip: str, pool: DhcpPool) -> bool:
    try:
        addr = ipaddress.ip_address(ip)
        return addr in ipaddress.ip_network(pool.subnet, strict=False)
    except ValueError:
        return False


def upsert_leases(db, rows: list[ParsedLease], pools: list[DhcpPool], source: str) -> int:
    now = datetime.utcnow()
    count = 0
    for row in rows:
        if not row.ip_address or not row.mac_address:
            continue
        pool = next((item for item in pools if ip_in_pool(row.ip_address, item)), pools[0] if pools else None)
        existing = (
            db.query(DhcpLease)
            .filter(DhcpLease.mac_address == row.mac_address, DhcpLease.ip_address == row.ip_address)
            .first()
        )
        if existing is None:
            existing = db.query(DhcpLease).filter(DhcpLease.mac_address == row.mac_address).first()
        if existing:
            existing.ip_address = row.ip_address
            existing.hostname = row.hostname or existing.hostname
            existing.status = row.status
            existing.lease_end = row.expires.replace(tzinfo=None) if row.expires else existing.lease_end
            existing.last_seen_at = now
            existing.source = source
            if pool:
                existing.pool_id = pool.id
        else:
            db.add(
                DhcpLease(
                    pool_id=pool.id if pool else None,
                    ip_address=row.ip_address,
                    mac_address=row.mac_address,
                    hostname=row.hostname,
                    status=row.status,
                    lease_end=row.expires.replace(tzinfo=None) if row.expires else None,
                    last_seen_at=now,
                    source=source,
                )
            )
        count += 1
    db.commit()
    return count
